# -*- encoding: utf-8 -*-
from __future__ import annotations
from types import *
from typing import *


class BMVertSeq:
    def __class__(*args, **kwargs) -> Any: ...
    def __contains__(self, key, /): ...
    def __delattr__(self, name, /): ...
    def __dir__(self, /): ...
    __doc__: None
    def __eq__(self, value, /): ...
    def __format__(self, format_spec, /): ...
    def __ge__(self, value, /): ...
    def __getattribute__(self, name, /): ...
    def __getitem__(self, key, /): ...
    def __gt__(self, value, /): ...
    def __hash__(self, /): ...
    def __init__(self, /, *args, **kwargs): ...
    def __init_subclass__(self, /, *args, **kwargs): ...
    def __iter__(self, /): ...
    def __le__(self, value, /): ...
    def __len__(self, /): ...
    def __lt__(self, value, /): ...
    def __ne__(self, value, /): ...
    def __new__(self, value, /): ...
    def __reduce__(self, /): ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self, /): ...
    def __setattr__(self, name, value, /): ...
    def __sizeof__(self, /): ...
    def __str__(self, /): ...
    def __subclasshook__(self, /): ...
    def ensure_lookup_table(*args, **kwargs) -> Any: ...
    def index_update(*args, **kwargs) -> Any: ...
    layers: GetSetDescriptorType
    def new(*args, **kwargs) -> Any: ...
    def remove(*args, **kwargs) -> Any: ...
    def sort(*args, **kwargs) -> Any: ...



class BMEditSelSeq:
    def __class__(*args, **kwargs) -> Any: ...
    def __contains__(self, key, /): ...
    def __delattr__(self, name, /): ...
    def __dir__(self, /): ...
    __doc__: None
    def __eq__(self, value, /): ...
    def __format__(self, format_spec, /): ...
    def __ge__(self, value, /): ...
    def __getattribute__(self, name, /): ...
    def __getitem__(self, key, /): ...
    def __gt__(self, value, /): ...
    def __hash__(self, /): ...
    def __init__(self, /, *args, **kwargs): ...
    def __init_subclass__(self, /, *args, **kwargs): ...
    def __iter__(self, /): ...
    def __le__(self, value, /): ...
    def __len__(self, /): ...
    def __lt__(self, value, /): ...
    def __ne__(self, value, /): ...
    def __new__(self, value, /): ...
    def __reduce__(self, /): ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self, /): ...
    def __setattr__(self, name, value, /): ...
    def __sizeof__(self, /): ...
    def __str__(self, /): ...
    def __subclasshook__(self, /): ...
    active: GetSetDescriptorType
    def add(*args, **kwargs) -> Any: ...
    def clear(*args, **kwargs) -> Any: ...
    def discard(*args, **kwargs) -> Any: ...
    def remove(*args, **kwargs) -> Any: ...
    def validate(*args, **kwargs) -> Any: ...



class BMLoopSeq:
    def __class__(*args, **kwargs) -> Any: ...
    def __delattr__(self, name, /): ...
    def __dir__(self, /): ...
    __doc__: None
    def __eq__(self, value, /): ...
    def __format__(self, format_spec, /): ...
    def __ge__(self, value, /): ...
    def __getattribute__(self, name, /): ...
    def __gt__(self, value, /): ...
    def __hash__(self, /): ...
    def __init__(self, /, *args, **kwargs): ...
    def __init_subclass__(self, /, *args, **kwargs): ...
    def __le__(self, value, /): ...
    def __lt__(self, value, /): ...
    def __ne__(self, value, /): ...
    def __new__(self, value, /): ...
    def __reduce__(self, /): ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self, /): ...
    def __setattr__(self, name, value, /): ...
    def __sizeof__(self, /): ...
    def __str__(self, /): ...
    def __subclasshook__(self, /): ...
    layers: GetSetDescriptorType



class BMFaceSeq:
    def __class__(*args, **kwargs) -> Any: ...
    def __contains__(self, key, /): ...
    def __delattr__(self, name, /): ...
    def __dir__(self, /): ...
    __doc__: None
    def __eq__(self, value, /): ...
    def __format__(self, format_spec, /): ...
    def __ge__(self, value, /): ...
    def __getattribute__(self, name, /): ...
    def __getitem__(self, key, /): ...
    def __gt__(self, value, /): ...
    def __hash__(self, /): ...
    def __init__(self, /, *args, **kwargs): ...
    def __init_subclass__(self, /, *args, **kwargs): ...
    def __iter__(self, /): ...
    def __le__(self, value, /): ...
    def __len__(self, /): ...
    def __lt__(self, value, /): ...
    def __ne__(self, value, /): ...
    def __new__(self, value, /): ...
    def __reduce__(self, /): ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self, /): ...
    def __setattr__(self, name, value, /): ...
    def __sizeof__(self, /): ...
    def __str__(self, /): ...
    def __subclasshook__(self, /): ...
    active: GetSetDescriptorType
    def ensure_lookup_table(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    def index_update(*args, **kwargs) -> Any: ...
    layers: GetSetDescriptorType
    def new(*args, **kwargs) -> Any: ...
    def remove(*args, **kwargs) -> Any: ...
    def sort(*args, **kwargs) -> Any: ...



class BMEdgeSeq:
    def __class__(*args, **kwargs) -> Any: ...
    def __contains__(self, key, /): ...
    def __delattr__(self, name, /): ...
    def __dir__(self, /): ...
    __doc__: None
    def __eq__(self, value, /): ...
    def __format__(self, format_spec, /): ...
    def __ge__(self, value, /): ...
    def __getattribute__(self, name, /): ...
    def __getitem__(self, key, /): ...
    def __gt__(self, value, /): ...
    def __hash__(self, /): ...
    def __init__(self, /, *args, **kwargs): ...
    def __init_subclass__(self, /, *args, **kwargs): ...
    def __iter__(self, /): ...
    def __le__(self, value, /): ...
    def __len__(self, /): ...
    def __lt__(self, value, /): ...
    def __ne__(self, value, /): ...
    def __new__(self, value, /): ...
    def __reduce__(self, /): ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self, /): ...
    def __setattr__(self, name, value, /): ...
    def __sizeof__(self, /): ...
    def __str__(self, /): ...
    def __subclasshook__(self, /): ...
    def ensure_lookup_table(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    def index_update(*args, **kwargs) -> Any: ...
    layers: GetSetDescriptorType
    def new(*args, **kwargs) -> Any: ...
    def remove(*args, **kwargs) -> Any: ...
    def sort(*args, **kwargs) -> Any: ...



class BMesh:
    def __class__(): ...
    def __delattr__(name, /): ...
    def __dir__(name, /): ...
    __doc__: str
    def __eq__(value, /): ...
    def __format__(value, /): ...
    def __ge__(value, /): ...
    def __getattribute__(name, /): ...
    def __gt__(value, /): ...
    def __hash__(): ...
    def __init__(*args, **kwargs): ...
    def __init_subclass__(*args, **kwargs): ...
    def __le__(value, /): ...
    def __lt__(value, /): ...
    def __ne__(value, /): ...
    def __new__(value, /): ...
    def __reduce__(value, /): ...
    def __reduce_ex__(value, /): ...
    def __repr__(): ...
    def __setattr__(name, value, /): ...
    def __sizeof__(name, value, /): ...
    def __str__(): ...
    def __subclasshook__(): ...
    def calc_loop_triangles(): ...
    def calc_volume(): ...
    def clear(): ...
    def copy(): ...
    edges: BMEdgeSeq
    faces: BMFaceSeq
    def free(): ...
    def from_mesh(): ...
    def from_object(): ...
    is_valid: bool
    is_wrapped: bool
    loops: BMLoopSeq
    def normal_update(): ...
    def select_flush(): ...
    def select_flush_mode(): ...
    select_history: BMEditSelSeq
    select_mode: Set
    def to_mesh(): ...
    def transform(): ...
    verts: BMVertSeq
